name: Docker Image CI

on:
    push:
        branches:
            - main
            - master
            - 'v*'
        paths:
            - '.github/workflows/ci.yml'
            - 'nginx/**'
            - 'socketio/**'
            - 'erpnext/**'
            - 'Dockerfile'

jobs:
    docker-build-push:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                version: [12]
                target: [erpnext, erpnext-nginx, erpnext-socketio]

        steps:
            - name: Checkout 🛎
              uses: actions/checkout@v2

            - name: Docker meta
              if: success()
              id: docker_meta
              uses: crazy-max/ghaction-docker-meta@v1
              with:
                  images: fengsiio/${{matrix.target}}
                  tag-semver: |
                      {{ version }}
                      {{major}}.{{minor}}

            - name: Set up QEMU
              if: success()
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              if: success()
              uses: docker/setup-buildx-action@v1

            - name: Cache Docker layers
              if: success()
              uses: actions/cache@v2
              with:
                  path: /tmp/.buildx-cache
                  key: ${{ runner.os }}-buildx-${{ github.sha }}-${{matrix.target}}
                  restore-keys: |
                      ${{ runner.os }}-buildx-${{matrix.target}}

            - name: Login to Registry
              if: success()
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push
              if: success()
              uses: docker/build-push-action@v2
              with:
                  push: true
                  platforms: linux/amd64
                  target: ${{matrix.target}}
                  build-args: |
                    VERSION=${{ matrix.version }}
                  tags: ${{ steps.docker_meta.outputs.tags }}
                  labels: ${{ steps.docker_meta.outputs.labels }}
                  cache-from: type=local,src=/tmp/.buildx-cache
                  cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
